Create B827EBFFFEA488FE.json
ttn-zh/gateway-remote-config pull request #1681
Opened 2021-11-24 13:12 UTC by lostall2

2021-11-24 14:27 UTC, gonzalocasas commented on B827EBFFFEA488FE.json
> +    "contact_email": "",
please add your email here.

2021-11-24 14:28 UTC, gonzalocasas requested changes
email missing

2021-11-24 21:53 UTC, lostall2 reviewed
done

2021-11-26 09:31 UTC, gonzalocasas commented
Thanks!

2021-11-26 09:31 UTC, merged