Create B827EB4D73D3EFEF.json
ttn-zh/gateway-remote-config pull request #1766
Opened 2023-05-22 09:00 UTC by aefathabadi

2023-05-22 09:01 UTC, aefathabadi commented
please help me I want to create a ttn - gateway.

2023-05-23 16:13 UTC, gonzalocasas requested changes

2023-05-23 16:13 UTC, gonzalocasas commented on B827EB4D73D3EFEF.json
> +                "server_address": "router.eu.thethings.network",
This URL should be updated. This is the old v2 routers, please use the v3 ones and then we can merge.

2024-04-07 13:42 UTC, gonzalocasas commented
closing due to inactivity

2024-04-07 13:42 UTC, closed without merging